global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-services"
    static_configs:
      - targets: ["user-service:8000", "product-service:8000", "payment-service:8000"]
        labels:
          group: "production"